## **Al-Khair Institute of Technology**
## **Assignment no: 4**
## **Numpy_Basics**
## **Prepared By: Sheikh Saqib**


**Q1) Create an (m × n) matrix with given conditions + extract rows & 3rd column + justify 1D output**
**Conditions you must satisfy:**
**Each row is sorted (non-decreasing)**

**First element of every row > last element of previous row**
**This means the entire matrix acts like a sorted list spread across rows.**

In [ ]:
#Code + Explanation
import numpy as np

# Creating a matrix that satisfies both conditions
# Example: 3x4 matrix
matrix = np.array([
    [1,  3,  5,  7],      # sorted row
    [10, 12, 14, 16],     # first element 10 > last row's last value 7
    [20, 22, 24, 26]      # same rule
])

print("Matrix:\n", matrix)

# Extract all rows, only the 3rd column (index 2)
third_col = matrix[:, 2]
print("\nExtracted third column:", third_col)
print("Shape:", third_col.shape)

Matrix:
 [[ 1  3  5  7]
 [10 12 14 16]
 [20 22 24 26]]

Extracted third column: [ 5 14 24]
Shape: (3,)


**Why the Output Becomes 1D?**

**Even though matrix is 2D, the slicing:**

In [4]:
matrix[:, 2]

# selects:
# All rows
# One single column

# Mathematically, one column is no longer a 2D structure unless you explicitly keep the dimension.
# So NumPy removes the dimension automatically, giving you a shape:

(3,)

# Not:

(3,1)

# Because NumPy removes any dimension where only 1 column is selected using:.
# This is called “dimension squeezing.”

# If you WANT a 2D column, you must force it:

matrix[:, 2:3]

array([[ 5],
       [14],
       [24]])

**Q2) Two-Sum Problem**

**Task: Find two indices whose values add up to a target.**

In [ ]:

import numpy as np

nums = np.array([2, 7, 11, 15])
target = 9

# Dictionary-based solution (efficient)
seen = {}
for i, num in enumerate(nums):
    diff = target - num
    if diff in seen:
        print("Indices:", seen[diff], i)
        break
    seen[num] = i



Indices: 0 1


Why this works?

•	We store numbers in a dictionary

•	For each number, we check if the "other number" (target – current) exists

•	Guaranteed 1 solution

•	Cannot use same index twice — this method prevents that



**Q3) Create 1D integer array & print its properties**

In [ ]:

import numpy as np

arr = np.arange(10)   # 0 to 9
print("Array:", arr)

print("dtype:", arr.dtype)
print("shape:", arr.shape)
print("size:", arr.size)
print("itemsize:", arr.itemsize)
print("nbytes:", arr.nbytes)

# Comment:
# dtype is int32 (or int64 depending on system) because NumPy chooses the most memory-efficient integer type.


Array: [0 1 2 3 4 5 6 7 8 9]
dtype: int64
shape: (10,)
size: 10
itemsize: 8
nbytes: 80


**Q4) Convert 1D → 2D Matrix (3×4) + Access element**

In [8]:

import numpy as np

arr = np.arange(12)
matrix = arr.reshape(3, 4)

print("Matrix:\n", matrix)

# element at row 2, column 1
print("\nElement at (2,1):", matrix[2, 1])  # zero-indexed


Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Element at (2,1): 9


**Q4 (Second Part) Extract rows and columns**

In [12]:

print("Second row:", matrix[1])                 # row index 1

print("\nFirst two columns:\n", matrix[:, :2])  # all rows, col 0–1

print("\nEvery second column (step=2):\n", matrix[:, ::2])



Second row: [4 5 6 7]

First two columns:
 [[0 1]
 [4 5]
 [8 9]]

Every second column (step=2):
 [[ 0  2]
 [ 4  6]
 [ 8 10]]


**Q5) Compute mean, median, variance, std**

In [ ]:

import numpy as np

arr = np.array([2, 4, 4, 6, 10, 12])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Std Dev:", np.std(arr))

# Interpretation:
if np.std(arr) > 3:
    print("Data is widely spread out.")
else:
    print("Data is closely packed (low variance).")
    


Mean: 6.333333333333333
Median: 5.0
Variance: 12.555555555555555
Std Dev: 3.5433819375782165
Data is widely spread out.


**Q6) Matrix Inverse + verify A @ A_inv = Identity**

In [10]:

import numpy as np

A = np.array([
    [2, 1],
    [5, 3]
], dtype=float)

A_inv = np.linalg.inv(A)
product = A @ A_inv

print("A:\n", A)
print("\nInverse of A:\n", A_inv)
print("\nProduct (A @ A_inv):\n", product)


A:
 [[2. 1.]
 [5. 3.]]

Inverse of A:
 [[ 3. -1.]
 [-5.  2.]]

Product (A @ A_inv):
 [[1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00]]


**Q7) 3D Arrays — sums on axes + transpose**

In [11]:

import numpy as np

arr3d = np.arange(2*3*4).reshape(2, 3, 4)
print("3D array:\n", arr3d)

print("\nSum over axis=0:\n", np.sum(arr3d, axis=0))  # depth
print("\nSum over axis=1:\n", np.sum(arr3d, axis=1))  # rows

# transpose to shape (4,2,3)
new_arr = np.transpose(arr3d, (2, 0, 1))
print("\nNew shape after transpose:", new_arr.shape)


3D array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Sum over axis=0:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

Sum over axis=1:
 [[12 15 18 21]
 [48 51 54 57]]

New shape after transpose: (4, 2, 3)
